version: "3.7"
services:
  server:
    image: "jiyeon12345/photolink-backend:latest"
    build: .
    container_name: photolink-backend
    restart: unless-stopped
    volumes:
      - appdata:/app
    networks:
      - app
    ports:
      - "2727:2727"